

dubbo:
  application:
    name: provider-tickt
  registry:
    address: zookeeper://192.168.200.160:2181
    timeout: 30000
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.wf.ticket.service.impl
server:
  port: 8080
